---
title: "chan_assignment1"
author: "Delores Chan"
date: "2024-02-14"
output: html_document
---

# 1. Why do you want to take this course? 
## I want to take this course to clean up and sharpen my coding skills. Revieiwng the best practices is really helpful and I want to implement these skills into my future work. I would love to get better at looping and understanding looping -- I took Natural Resource Econ last quarter and we used nloptr and had to write our own functions (all of which included for loops) and this always tripped me up. I want to learn new skills to help me code better in R so that it can be applicable to my future work. I don't plan on taking modeling next quarter, but I think a really solid set of coding skills would be largely beneficial to me as I figure out my future career. 

# 2. What is you data science background? 
## I don't have a very extensive data science background. Before coming to Bren, I had never coded before. My first experience coding was in 206 and there was definitely a steep learning curve. Since then, I've taken Natural Resource Econ with Andrew Plantinga which was coding heavy with the package nloptr. That was also challenging, but by the end of the class, I did feel like I had a decent grasp on the package and how to use it. In addition, I've been coding for my group project by running a sentiment analysis on public comments that were submitted. This wasn't too difficult, but just required a lot of data cleaning. Overall, I think I have a basic grasp of coding and data science, but I would love to build upon it and learn more. 